name: 'VillagerAnnouncer'
version: '${version}'
description: '${description}'
authors: [ 'PenalBuffalo' ]
website: 'https://github.com/stumper66/VillagerAnnouncer'

main: 'io.github.stumper66.villagerannouncer.VillagerAnnouncer'
api-version: '1.16'
load: 'POSTWORLD'

softdepend:
  - DiscordSRV

commands:
  villagerannouncer:
    description: Manage Villager Announcer
    aliases: [ va ]

permissions:
  villagerannouncer.*:
    description: 'Access to all Villager Announcer commands.'
    default: op
    children:
      villagerannouncer.toggle: true

  villagerannouncer.toggle:
    description: 'Allows a player to toggle Villager Announcer sounds for themselves.'
    default: true
